config/routes.rb
Myapp::Application.routes.draw do

  get "home/index"

root to: 'posts#index'

  resources :posts do
    collection do
      get 'choose_revert'
      get 'revert'
    end
  end

  get "static_pages/about"
  get "static_pages/contact"
  patch "static_pages/update" => 'static_pages#update'
  get "session/new"
  post "session/create" => "session#create"
  delete "session/destroy" => "session#destroy"
  get "login" => "session#new"

  get "passwords/change" => "passwords#change"
  post "passwords/update" => "passwords#update"

  get ":post_url" => "posts#show_url"

end

app/models/backup.rb
class Backup < ActiveRecord::Base
  def filename
    "#{self.created_at.strftime("%Y-%m-%dT%H:%M:%S")}.sql"
  end

  def display_name
    "#{self.created_at.in_time_zone("Central Time (US & Canada)").strftime("%B %-d, %Y, %I:%M:%S %P")}"
  end
end

app/models/blurb.rb
class Blurb < ActiveRecord::Base
end

app/models/hit.rb
class Hit < ActiveRecord::Base
end

app/models/password.rb
class Password < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true
  validates_uniqueness_of :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def admin_login_required
    redirect_to controller: "session", action: "new" unless admin?
  end

  def admin?
    return (session[:admin] == true)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :admin_login_required

  def change
    @password = Password.new
  end

  def update
    if params[:password][:password] == params[:password][:confirmation]
      @password = Password.all.first
      @password.digest = Digest::SHA1.base64digest params[:password][:password]
      @password.save
      redirect_to root_path
    else
      @password = Password.new
      flash.now[:info] = "Passwords must match"
      render "change"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :increment_hits
  before_action :admin_login_required, :except => [:index, :show, :show_url]
  after_action :backup_db, :only => [:create, :update, :destroy]

  def index
    @posts = Post.all.order("created_at desc")
    if session[:admin]
      puts "ADMIN SET!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    else
      puts "ADMIN NOT SET!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def show_url
    @post = Post.where(:url => params[:post_url]).first
    render "show"
  end

  def new
    @post = Post.new
  end

  def create
    _url = params[:post][:title].downcase.gsub(/\s/, '-').gsub(/[^0-9A-Za-z\-]/, '')
    _content = params[:post][:content]
    @post = Post.create(title: params[:post][:title], content: _content, url: _url)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.title = params[:post][:title]
    @post.content = params[:post][:content]
    if @post.save
      redirect_to @post
    else
      render "edit", id: @post.id
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    @posts = Post.all.order("created_at desc")
    render "index"
  end

  def increment_hits
    puts "increment_hits called"
    unless session[:hit_counted] == "true"
      session[:hit_counted] = "true"
      hits = Hit.first
      hits.hits += 1
      hits.save
      puts "New Hits: #{hits.hits}"
    end
  end

  def choose_revert
    @backups = Backup.order("created_at desc").all
  end

  def revert
    backup = Backup.find(params[:backup_id])
    system "mysql -uroot -pCsmok2396! #{ENV['RAILS_ENV'] == 'development' ? 'concerning_college_development' : 'rails'} < db/backups/#{ENV['RAILS_ENV'] == 'development' ? 'development' : 'production'}/#{backup.filename}" if !backup.nil?
    redirect_to root_path
  end

  def backup_db
    backup = Backup.create
    puts "mysqldump -uroot -pCsmok2396! #{ENV['RAILS_ENV'] == 'development' ? 'concerning_college_development' : 'rails'} > db/backups/#{ENV['RAILS_ENV']}/#{backup.filename}"
    system "mysqldump -uroot -pCsmok2396! #{ENV['RAILS_ENV'] == 'development' ? 'concerning_college_development' : 'rails'} > db/backups/#{ENV['RAILS_ENV'] == 'development' ? 'development' : 'production'}/#{backup.filename}"
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    @password = Password.new
  end

  def create
    attempted_pass = Digest::SHA1.base64digest params[:password][:password]
    if attempted_pass == Password.all.first.digest
      session[:admin] = true
      redirect_to root_path
    else
      @password = Password.new
      render "new"
    end
  end

  def destroy
    session.delete(:admin)
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :admin_login_required, :except => [:about, :contact]

  def about
    @blurb = Blurb.where(:page => "About").first
    @is_admin = admin?
  end

  def contact
    @blurb = Blurb.where(:page => "Contact").first
    @is_admin = admin?
  end

  def update
    @blurb = Blurb.find(params[:id])
    @blurb.content = params[:blurb][:content]
    @blurb.save
    flash.now[:info] = "Blurb updated!"
    render @blurb.page.downcase
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/home/index.html.erb
<style type="text/css" media="screen">
      body {
	text-align:center;
        margin: 0;
        margin-bottom: 25px;
        padding: 0;
        background-color: #f0f0f0;
        font-family: "Lucida Grande", "Bitstream Vera Sans", "Verdana";
        font-size: 13px;
        color: #333;
      }

      h1 {
        font-size: 28px;
        color: #000;
      }

</style>
<h1 align="center">DigitalOcean Rails Application</h1>
<img src="assets/rails.png" align="center"><br/>
<p>This file is located in /home/rails/app/views/home/index.html.erb</p>

Your application root is located in: <%= Rails.root.to_s %><br>

Ruby version: <%= RUBY_VERSION %><br>

Rails version: <%= Rails.version %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Concerning College</title>
  <meta name="description" content="<%= Blurb.where(:page => "About").first.content %>" >
  <meta name="keywords" content="concerning college, college, Mark Lerner, Sun Current" >
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class = "wrapper">
  <div class = "headdiv">
    <p class = "headtext">Concerning College</p>
    <p class = "headtext headsubtext">by Mark Lerner</p>
  </div>
  <div class = "bodydiv">
    <table class = "bodytable">
      <tr>
        <td class = "bodytd" id = "sidetd">
          <div class = "sidediv">
            <div class = "linkdiv l1">
              <div class = "linkwrapper"><%= link_to "HOME", posts_path %></div>
            </div>
            <div class = "divider"></div>
            <div class = "linkdiv l2">
              <div class = "linkwrapper"><%= link_to "ABOUT", static_pages_about_path %></div>
            </div>
            <div class = "divider"></div>
            <div class = "linkdiv l3">
              <div class = "linkwrapper"><%= link_to "CONTACT", static_pages_contact_path %></div>
            </div>
          </div>
        </td>

        <td class = "bodytd" id = "maintd">
          <div class = "maindiv">
            <% if session[:admin] == true %>
                <div class = "hits_div">Hits: <%= Hit.first.hits %></div>
                <div class = "nav_div">
                  <%= link_to "New Post", new_post_path, :class => "nav_link" %>
                  <%= link_to "Change Password", passwords_change_path, :class => "nav_link"%>
                  <%= link_to "Database Reversion", choose_revert_posts_path, :class => "nav_link" %>
                  <%= link_to "Logout", session_destroy_path, :method => :delete, :class => "nav_link" %>
                </div>
            <% end %>
            <%= yield %>
          </div>
        </td>
      </tr>
    </table>
  </div>
  <div class = "footer">Authored by Mark Lerner</div>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<div class = "form_div">
	<p class = "form_label">Instructions:</p>
	<ol class = "instructions">
		<li> Open up your internet browser, and go to Google.com </li>
		<li> Search Google for something like "edina sun current mark lerner", and find the column you're looking for</li>
		<li> Highlight the title of the article, and then click "Edit" at the top of the computer screen, and then "Copy"</li>
		<li> Click on the ConcerningCollege tab to get back to the New Post page you already have open</li>
		<li> Click inside the "Title" box, click "Edit" at the top of your screen, and then "Paste"</li>
		<li> Repeat this process for the body of the column, copying and pasting into the "Content" box</li>
		<li> IMPORTANT! Click "Create new post" at the bottom of the page to actually submit the post</li>
	</ol>
	<% if post.errors.any? %>
	<div class = "error_message_div">
		<ul>
		<% post.errors.each do |e, message| %>
				<li class = "error_message">Submission error: <%= "#{e} #{message}" %></li>
		<% end %>
		</ul>
	</div>
	<% end %>
	<%= form_for post, url: { controller: "posts", action: action}	do |f|%>

			<p class = "form_label">Title</p>
			<%= f.text_field :title %>

			<p class = "form_label">Content</p>
			<%= f.text_area :content, :rows => "20", :cols => "40" %>

			<br>

			<%= f.submit submit_text %>
	<% end %>
</div>

app/views/posts/_post_div.html.erb
<div class = "post_div">
  <% if session[:admin] == true %>
      <div class = "nav_div">
        <%= link_to "Delete Post", post_path(post), :method => :delete, :class => "nav_link" %>
        <%= link_to "Edit Post", edit_post_path(post), :class => "nav_link" %>
      </div>
  <% end %>
  <p class = "title_text"><a class = "title_text" href = "/<%= post.url %>"><%= post.title %></a></p>
  <p class = "byline_text"><%= post.created_at.strftime("Posted on %A, %B %e, %Y") %></p>
  <div class = "little_divider"></div>
  <%= simple_format post.content, :class => "content_text" %>
</div>
<div class = "comments_link" style = "margin-bottom: 10px;"><a class = "comments_link" href = "mailto:concerningcollege@gmail.com">Email the Author</a></div>
<div class = "share_text">Share this article: <%= "ConcerningCollege.com/#{post.url}" %></div>
<div class = "comments_link"><a class = "comments_link" href = "/<%= post.url %>">View Comments</a></div>
<div class = "divider"></div>

app/views/posts/choose_revert.html.erb
<p class = "title_text">Revert database to previous state.</p>
<p class = "title_text">Please select the time to revert to.</p>
<p class = "title_text">(Contact webmaster to undo reversion)</p>
<ul class = "backup_list">
  <% @backups.each do |backup| %>
    <li class = "backup_li">
      <%= link_to backup.display_name, revert_posts_path(:backup_id => backup.id), :class => "backup_link" %>
    </li>
  <% end %>
</ul>

app/views/posts/edit.html.erb
 <p class = "title_text">Edit Post</p>
  <%= render "form", :post => @post, :action => "update", :submit_text => "Update Post" %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <%= render "post_div", :post => post %>
<% end %>

app/views/posts/new.html.erb
 <p class = "title_text">Create New Post</p>
  <%= render "form", :post => @post, :action => "create", :submit_text => "Create New Post" %>

app/views/posts/show.html.erb
<%= render "post_div", :post => @post %>
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'concerningcollege';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<div class = "form_div">
  <p class = "title_text">Log In</p>
  <%= form_for @password, url: session_create_url do |f| %>
      <p class = "form_label">Please Enter Password</p>
      <%= f.password_field :password %>

      <br>

      <%= f.submit "Log In" %>
  <% end %>
</div>

app/views/static_pages/_blurb.html.erb
<div class = "blurb_div">
  <p class = "title_text"><%= blurb.page %></p>
  <%= simple_format blurb.content, :class => "content_text"%>
</div>

app/views/static_pages/_form.html.erb
<div class = "form_div">
  <p class = "title_text">Update Blurb: <%= blurb.page %></p>
  <%= form_for blurb, url: { :controller => "static_pages", :action => "update"} do |f| %>
      <p class = "form_label">Content:</p>
      <%= f.text_area :content, :rows => "10", :cols => "30" %>

      <%= hidden_field_tag :id, blurb.id %>

      <br>

      <%= f.submit "Update" %>
  <% end %>
</div>

app/views/static_pages/about.html.erb
<% if flash.any? %>
    <p class = "info"><%= flash[:info] %></p>
<% end %>
<% if @is_admin %>
    <%= render "form", :blurb => @blurb %>
<% else %>
    <%= render "blurb", :blurb => @blurb %>
<% end %>

app/views/static_pages/contact.html.erb
<% if flash.any? %>
    <p class = "info"><%= flash[:info] %></p>
<% end %>
<% if @is_admin %>
    <%= render "form", :blurb => @blurb %>
<% else %>
    <%= render "blurb", :blurb => @blurb %>
<% end %>